apiVersion: apps/v1
kind: Deployment
metadata:
  name: schahid-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schahid
  template:
    metadata:
      labels:
        app: schahid
    spec:
      containers:
        - name: schahid-app-hello
          image: soufiane01/schahid:v2
          ports:
            - containerPort: 9090
