apiVersion: v1
kind: Service
metadata:
  name: schahid-app
  namespace: dev
spec:
  selector:
    app: schahid
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30007
  
